---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# d3-resources

<!-- badges: start -->

<!-- badges: end -->

## Official

-   <https://d3js.org/>

-   [D3: Data-Driven Documents](https://github.com/d3/d3) - Github

-   [r2d3: R Interface to D3 Visualizations](https://rstudio.github.io/r2d3/index.html)

## People

-   [Amelia Wattenberger](https://wattenberger.com/)

## Introductions

-   [Intro to D3.js from Square](http://square.github.io/intro-to-d3/)

-   [D3 in Depth from Peter Cook](https://www.d3indepth.com/)

-   [Dashing D3.js](https://www.dashingd3js.com/)

-   [Visualizations in D3 - R Pruim](https://rpruim.github.io/D3/notes/)

-   [An introduction to d3.js in 10 basic examples - D3.js Graph Gallery](https://d3-graph-gallery.com/intro_d3js.html)

-   [Drawing axis in d3.js - D3.js Graph Gallery](https://d3-graph-gallery.com/graph/custom_axis.html)

-   [How to "learn D3" in 2023 - Connor Rothschild](https://www.connorrothschild.com/viz)

-   [Learn D3 - Mike Bostock](https://observablehq.com/collection/@d3/learn-d3)

-   [Let's Make a Bar Chart - Mike Bostock](https://observablehq.com/collection/@d3/lets-make-a-bar-chart)

## Courses

-   [Fullstack D3 and Data Visualization](https://www.newline.co/fullstack-d3)
-   Introduction to D3 Course - Paul Buffa ([Youtube Playlist](https://www.youtube.com/playlist?list=PLOHIJAFwtkEcK_mLLScnX2B-yHDjzSxuR), [Observable Notebooks](https://observablehq.com/@observablehq/introduction-to-d3-course?collection=@observablehq/introduction-to-d3-course))

## Technical Basics

### Data and Selection Joins

-   [Thinking with Joins - Mike Bostock](https://bost.ocks.org/mike/join/)

-   [Selection Join - Mike Bostock](https://observablehq.com/@d3/selection-join)

### Margins

-   [Margin Convention - Mike Bostock](https://observablehq.com/@d3/margin-convention)

## Other

-   [State of Java Script 2022 Survey](https://2022.stateofjs.com/en-US)
-   [Using Observable in Quarto](https://quarto.org/docs/computations/ojs.html)

## Small Multiples / Facets

-   [Facets in Observable Plot](https://observablehq.com/plot/features/facets) - Observable Plot Documentation

-   [Local Variables - Mike Bostock](https://gist.github.com/mbostock/e1192fe405703d8321a5187350910e08)

-   [Small Multiples Examples - Mike Bostock](https://gist.github.com/mbostock/1157787)

-   [What is the best way to create small multiples in d3.js v6? - Stack Overflow](https://stackoverflow.com/questions/66230918/what-is-the-best-way-to-create-small-multiples-in-d3-js-v6)

-   [Small multiple for line chart](https://d3-graph-gallery.com/graph/line_smallmultiple.html) - D3.js Graph Gallery

-   [Small Multiples - NYU Visualization](https://observablehq.com/@nyuvis/small-multiples)

-   [Interactive and Responsive Small Multiples with D3 - Colin Eberhardt](https://blog.scottlogic.com/2017/04/05/interactive-responsive-small-multiples.html)

-   [Small Multiples with d3 - Jonathan Soma](https://jonathansoma.com/tutorials/d3/small-multiples/)

-   [Using nested data to create small multiples - Henry Lau](https://www.henrylau.co.uk/2021/09/08/small-multiples/)

-   [D3.js merge() extended - small multiples - Bryony Miles](https://www.codementor.io/@milesbryony/d3-js-merge-extended-small-multiples-14efbozjk5)

-   [A single d3.js V4 chart with 'small multiples' along single categorical x-axis - Carl V Lewis](https://gist.github.com/carlvlewis/8a5b1cc987217607a47bd7d4e0fffacb)

-   [How to create a 'facetplot' in d3.js? - Stack Overflow](https://stackoverflow.com/questions/65499073/how-to-create-a-facetplot-in-d3-js)

# Cognos Analytics

## Official

-   [Custom Visualizations Developer - IBM Cognos Analytics 12.0.x Documentation](https://www.ibm.com/docs/en/cognos-analytics/12.0.0?topic=developing-custom-visualizations-developer)

-   [Customvis-lib IBM Github](https://github.com/IBM/ca_customvis)

-   [customvis-lib API Reference](https://ibm.github.io/ca_customvis/docs/11.1.x/)

-   [Custom Visualizations Developer - IBM Cognos Analytics 12.0.x Developing Manual](https://www.ibm.com/docs/en/SSEP7J_12.0.0/pdf/dg_custom_vis.pdf)

-   [IBM Accelerator Catalog](https://accelerator.ca.analytics.ibm.com/)

    -   Select "Products and Services" -\> "IBM Cognos Analytics"

    -   Select "Accelerator Type" -\> "Visualization"
